common:
    lid_topic: "/kitti/velo/pointcloud"
    imu_topic: "/kitti/oxts/imu"

preprocess:
    lidar_type: 2 # Velodyne LiDAR
    scan_line: 64
    blind: 2
    feature_extract_en: false

initialization:
    cut_frame_num: 1 # must be positive integer
    orig_odom_freq: 10
    mean_acc_norm: 9.81 # 1: for livox built-in IMU
    online_refine_time: 15.0
    data_accum_length: 800
    Rot_LI_cov: [0.00005, 0.00005, 0.00005]
    Trans_LI_cov: [0.0001, 0.0001, 0.0001]

mapping:
    filter_size_surf: 0.4
    filter_size_map: 0.4
    gyr_cov: 0.5
    acc_cov: 0.5
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range: 100.0

publish:
    path_en: true
    scan_publish_en: true # false: close all the point cloud output
    dense_publish_en: true # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval:
        -1 # how many LiDAR frames saved in each pcd file;
        # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
